# Generated by Django 5.0.2 on 2025-07-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_remove_userprofile_bio_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add a book'), ('can_change_book', 'Can change a book'), ('can_delete_book', 'Can delete a book')]},
        ),
    ]
